import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { Spinner } from "@nextui-org/react";
import { Suspense } from "react";

import NavBar from "@/components/navBar/NavBar";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <header>
          <NavBar />
        </header>
        <Providers>
          <main className="mx-5 mt-3">{children}</main>
        </Providers>
        <footer></footer>
      </body>
    </html>
  );
}
